const messages = {
    EMAIL_ALREADY_REGISTERED: "Email already registered",
    SIGNUP_FAILED: "Signup failed. Please try again.",
    LOGIN_SUCCESSFULL: "Login successful!",
    INTERNAL_SERVER_ERROR: "Internal server error.",
    SIGNUP_SUCCESSFULL: `Signup successful! Please check your email`,
    USER_NOT_FOUND: "User not found",
    DRIVER_NOT_FOUND: "Driver not found",
    ACCESS_DENIED: "Access Denied",
    INVALID_TOKEN: "Invalid Token",
    VERIFY_EMAIL_FIRST: "Please verify your email first.",
    INVALID_CREDENTIALS: "Invalid credentials",
    PROFILE_UPDATED: "Profile updated successfully!",
    NO_PROFILE_CHANGES: "No changes made to the profile.",
    PASSWORD_REQUIRED: "Both old and new passwords are required",
    INCORRECT_OLD_PASSWORD: "Incorrect old password",
    PASSWORD_CHANGED: "Password changed successfully",
    PASSWORD_CHANGE_FAILED: "Unable to change password",
    RECOVERY_EMAIL_SENT: "A recovery email has been sent to your email address to reset your password",
    PASSWORD_UPDATED: "Password updated successfully!",
    DRIVER_DOCUMENT_CHANGE_REQUEST_SUCCESSFULL: "Document change request submitted successfully!",
    DRIVER_DOCUMENT_CHANGE_REQUEST_FAILED: "Document change request failed!",
    USER_CREATED: "User created successfully.",
    DRIVER_CREATED: "Driver created successfully.",
    DATA_RETRIEVED: "Data retrieved successfully.",
    PACKAGE_SENT: "Package sent successfully.",
    SOMETHING_WENT_WRONG: "Something went wrong!.",
    PICKUP_ADDRESS_NOT_FOUND: "Pickup address not found.",
    PICKUP_ADDRESS_CREATED: "Pickup address created successfully.",
    PICKUP_ADDRESS_UPDATED: "Pickup address updated successfully.",
    PICKUP_ADDRESS_DELETED: "Pickup address deleted successfully.",
    DROPUP_ADDRESS_NOT_FOUND: "Dropup address not found.",
    DROPUP_ADDRESS_CREATED: "Dropup address created successfully.",
    DROPUP_ADDRESS_UPDATED: "Dropup address updated successfully.",
    DROPUP_ADDRESS_DELETED: "Dropup address deleted successfully.",
};

export default messages